language: generic
sudo: false
dist: trusty
branches:
  only:
    - master
    - "/^[0-9].*?-[0-9]{8}$/"
addons:
  apt:
    packages:
      - mingw-w64
      - curl
      - gettext
      - jq
      - git
      - p7zip-full
script:
  - ./build
deploy:
  provider: releases
  file: mk.exe
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  verbose: true
  on:
    tags: true
env:
  secure: rf/dxT+p/o6TbXmgRcZ4VnDaIO2rWSVxWQkm5Tw9pnSkwKUcd2zh9y+aOSzV/1M6WVa8bxk5Uexe1386X9idW1XrOkyueRtJfgorK5azTh1/j2FFkhgym7vw/cM3YJNEhWrpP/eb5jeESG19hXOkCcaez9b92IeUtxNQ3hcUnXFefptYTHKRQopImdzTBe3xfBwIH9Cx+deiSy0LnqMdnAQ+lh8vGIWqb4AiP5rUII/J9JwmyOhwNAIovuO3zI5cy0jAlIOrviKVaNviILcHVv5STIwlAbZfiQV1+VFWaChkm+SvvCy8WXQytdP2oC5M0CP0ZtbL+ZWUnCd7BH7PfORnKZYYvJEIjEKlwy05Y4wO7w+4fjYAaxEvUhyyr5WQvf4Uvf66Si5GKRr+fBHOaLjAQvwf41wieq1PnrgnvZlqW57H25e3zsy9utQXCNqxj2MU/hrP0sHzfC8c60umaAFx7rr5De5wuA2JpdGbOOPs/rHK8VBxE/JRnztmJ5HlPRZ2cpYIe2Z7Q3C5wbA1aLKcFVTOMNZWeV2KtuGUATpjKKcoWrpcJ3F6+zyllulB6V+Lgz7h9hkxUtWuIOQpPckY5qrdyfOvnnTeBrk5/daYZIFfnS7dzQ5K4scdbLwvJe2NTAlqU56Z3v8P2YNDzE5r9t038W7ILMtHNXiFZYE=
